//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class MMSearchBarDisplayController;

@class UIAlertViewDelegate;

@class CrossfadeAnimationController, FindContactSearchViewCellInfo, MMTableViewInfo, NSString, QRCodeCardView, UIButton, UILabel, UIView;

@interface AddFriendEntryViewController : UIViewController <UIAlertViewDelegate>
{
    FindContactSearchViewCellInfo *m_headerSearchView;
    UIView *m_searchFooterView;
    UIButton *m_myQRCodeBtn;
    UILabel *m_myNameLabel;
    QRCodeCardView *m_myQRCodeCard;
    UIButton *m_myQRCodeCardBackground;
    NSString *m_nsUserNameToFind;
    MMTableViewInfo *m_tableViewInfo;
    CrossfadeAnimationController *m_transitionInstance;
}

@property(retain, nonatomic) NSString *m_nsUserNameToFind; // @synthesize m_nsUserNameToFind;
- (void)onRadarSearchCreateViewShow;
- (void)onRadarSearchViewShow;
- (void)touchesBegan_TableView:(id)arg1 withEvent:(id)arg2;
- (void)onCancel:(id)arg1;
- (void)viewDidLoad;
- (void)viewDidLayoutSubviews;
- (void)initLeftButton;
- (void)initView;
- (void)initTitle;
- (void)initTableView;
- (void)updateViewWhenSelectTab:(BOOL)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (void)onSelectQQCell:(id)arg1;
- (void)onSelectCell:(id)arg1;
- (void)makeCell:(id)arg1 CellInfo:(id)arg2;
- (void)onSelectGoogleContactCell:(id)arg1;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(int)arg2;
- (void)dealloc;
- (id)init;
- (void)reloadData;
- (void)initSearchFooterView;
- (void)layoutSearchFooterView;
- (void)onShowMyQrCode;
- (void)onHideMyQrCode;
- (void)pluginsChanged:(id)arg1;
- (unsigned long)getBottleUnreadCountAtTarbar;
- (unsigned long)getBottleUnreadCount;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

