//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

// #import "UINavigationController.h"
@class UINavigationController;
@class UIViewController;

@interface MMUINavigationController : UINavigationController
{
    UIViewController *_popingViewController;
}

- (void)layoutViewsForTaskBar;
- (void)viewWillLayoutSubviews;
- (void)viewDidLoad;
- (void)viewWillAppear:(BOOL)arg1;
- (void)dealloc;
- (id)popViewControllerAnimated:(BOOL)arg1;
- (id)DispatchPopViewControllerAnimated:(BOOL)arg1;

@end

